/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_android_potatofly_ffmpegdemo_MainActivity */

#ifndef _Included_com_android_potatofly_ffmpegdemo_MainActivity
#define _Included_com_android_potatofly_ffmpegdemo_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_android_potatofly_ffmpegdemo_MainActivity
 * Method:    avformatiofo
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_android_potatofly_ffmpegdemo_MainActivity_avformatiofo
  (JNIEnv *, jobject);
/*
 * Class:     com_android_potatofly_ffmpegdemo_MainActivity
 * Method:    avcodecinfo
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_android_potatofly_ffmpegdemo_MainActivity_avcodecinfo
  (JNIEnv *, jobject);
/*
 * Class:     com_android_potatofly_ffmpegdemo_MainActivity
 * Method:    avfilterinfo
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_android_potatofly_ffmpegdemo_MainActivity_avfilterinfo
  (JNIEnv *, jobject);
/*
 * Class:     com_android_potatofly_ffmpegdemo_MainActivity
 * Method:    configurationinfo
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_android_potatofly_ffmpegdemo_MainActivity_configurationinfo
  (JNIEnv *, jobject);
#ifdef __cplusplus
}
#endif
#endif
